### 错误类型

当你开发自己的Go应用的时候，有很多场景都会使你最终走向创建自己的错误。**error**数据类型就是帮助你来创建自己的错误的。

这一节会教你如何创建自己的错误变量。你会看到，为了创建一些新的错误变量，你需要使用Go标准库中`errors`包的`New()`函数。

展示这个过程的实例代码在`newError.go`文件中，会分两部分来看。第一部分是这样的：

```go
package main
import (
	"errors"
	"fmt" 
)
func returnError(a, b int) error {
	if a == b {
		err := errors.New("Error in returnError() function!") 
		return err
	} else {
		return nil
	} 
}
```

这里有很多有趣的事情。首先，你可以看到本书中第一次定义一个不是**main**函数。这个新的函数叫`returnError()`。其次，你可以看到`errrs.New()`函数的使用了，这个函数接受一个`string`值作为参数。最后，如果一个函数应该返回一个`error`变量但是没有返回，它就返回一个`nil`。

程序`newError.go`的第二部分是这样的：

```go
func main() {
	err := returnError(1, 2) if err == nil {
		fmt.Println("returnError() ended normally!") 
	} else {
		fmt.Println(err) 
	}
	err = returnError(10, 10) 
	if err == nil {
		fmt.Println("returnError() ended normally!") 
	} else {
		fmt.Println(err) 
	}
	if err.Error() == "Error in returnError() function!" {
		fmt.Println("!!") 
	}
}
```

从上面的代码看出，大部分时候，你需要检查`error`变量是否等于`nil`，然后采取相应的处理。这里还展示了`errors.Error()`函数的使用，这个函数允许你把一个`error`变量转化成字符串变量。这个函数可以使一个`error`变量和`string`变量做比较。

执行` newError.go`会生成以下输出：

```shell
$ go run newError.go 
returnError() ended normally! Error in returnError() function! 
!!
```

如果你试图比较一个`string`变量和一个`error`变量，却没有先转换`error`变量为`string`变量，那么Go编译器会发出下面的错误信息：

```shell
# command-line-arguments
./newError.go:33:9: invalid operation: err == "Error in returnError() function!" (mismatched types error and string)
```

### 